"""create_sessions

Revision ID: cc2b0dfccc2b
Revises: 966dafbc4356
Create Date: 2024-06-11 20:13:34.516969

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc2b0dfccc2b'
down_revision: Union[str, None] = '966dafbc4356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_sessions',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('movie_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('room_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('start_time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('end_time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='movie_sessions_pkey'),
                    sa.ForeignKeyConstraint(['movie_id'], [
                        'movies.id'], name='movie_sessions_movie_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['room_id'], [
                        'rooms.id'], name='movie_sessions_room_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
                    )
    # Add some data
    op.execute("""
        INSERT INTO movie_sessions VALUES 
            (1, 1, 1, '2024-06-11 12:00:00.000000', '2024-06-11 15:00:00.000000'),
            (2, 2, 2, '2024-06-11 12:00:00.000000', '2024-06-11 14:30:00.000000'),
            (3, 1, 2, '2024-06-11 15:00:00.000000', '2024-06-11 18:00:00.000000'),
            (4, 2, 1, '2024-06-11 14:30:00.000000', '2024-06-11 17:00:00.000000')
        """
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_sessions')
    # ### end Alembic commands ###
