"""create_tickets

Revision ID: ef9a58ebb3b1
Revises: cc2b0dfccc2b
Create Date: 2024-06-12 08:18:35.841585

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef9a58ebb3b1'
down_revision: Union[str, None] = 'cc2b0dfccc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('session_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('movie_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('room_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('seat_number', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('seat_row', sa.VARCHAR(length=1),
                              autoincrement=False, nullable=True),
                    sa.Column('price', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='tickets_pkey'),
                    sa.ForeignKeyConstraint(['movie_id'], [
                        'movies.id'], name='ticket_movie_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['room_id'], [
                        'rooms.id'], name='ticket_room_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], [
                        'users.id'], name='ticket_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['session_id'], [
                        'movie_sessions.id'], name='ticket_movie_sessions_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
